In [2]:
import pandas as pd

file_path = '/HRDataset_v14.csv'
df = pd.read_csv(file_path)
print(df.head())

              Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026          0                0         1
1  Ait Sidi, Karthikeyan     10084          1                1         1
2         Akinkuolie, Sarah  10196          1                1         0
3              Alagbe,Trina  10088          1                1         0
4          Anderson, Carol   10069          0                2         0

   EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Salary  ...  \
0            1       5            4                       0   62506  ...
1            5       3            3                       0  104437  ...
2            5       5            3                       0   64955  ...
3            1       5            3                       0   64991  ...
4            5       5            3                       0   50825  ...

      ManagerName  ManagerID RecruitmentSource PerformanceScore  \
0  Michael Albert       22.0          LinkedIn          Exceeds
1      Simon Roup        4.0            Indeed      Fully Meets
2  Kissy Sullivan       20.0          LinkedIn      Fully Meets
3    Elijiah Gray       16.0            Indeed      Fully Meets
4  Webster Butler       39.0     Google Search      Fully Meets

   EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0              4.60               5                    0
1              4.96               3                    6
2              3.02               3                    0
3              4.84               5                    0
4              5.00               4                    0

  LastPerformanceReview_Date DaysLateLast30 Absences
0                  1/17/2019              0        1
1                  2/24/2016              0       17
2                  5/15/2012              0        3
3                   1/3/2019              0       15
4                   2/1/2016              0        2

[5 rows x 36 columns]

In [3]:
df.duplicated().sum()

0

In [4]:
df.shape

(311, 36)

In [5]:
df.isna().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Sex                             0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             207
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Sex                         311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   303 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 87.6+ KB

In [7]:
df.Sex.value_counts()

Sex
F     176
M     135
Name: count, dtype: int64

In [13]:
df.MaritalStatusID.value_counts()

MaritalStatusID
0    137
1    124
2     30
3     12
4      8
Name: count, dtype: int64

In [10]:
#Maping Sex - > M=0 , F=1
Sex_dic = {"male":0,"female":1}
df["Sex"] = df["Sex"].map(Sex_dic)
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [35]:
from sklearn.preprocessing import OneHotEncoder

# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

categorical_column = "MaritalDesc"

# Fit and transform the categorical column
one_hot_encoded = encoder.fit_transform(df[[categorical_column]])

# Create a DataFrame with the encoded columns
one_hot_df = pd.DataFrame(one_hot_encoded,
                          columns=encoder.get_feature_names_out([categorical_column]))

# Concatenate the one-hot encoded columns with the original DataFrame
df_sklearn_encoded = pd.concat([df.drop(categorical_column, axis=1), one_hot_df], axis=1)

# Print the result
print(f"One-Hot Encoded Data using Scikit-Learn:\n{df_sklearn_encoded.head()}\n")

One-Hot Encoded Data using Scikit-Learn:
              Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0       Adinolfi, Wilson  K  10026          0                0         1
1  Ait Sidi, Karthikeyan     10084          1                1         1
2         Akinkuolie, Sarah  10196          1                1         0
3              Alagbe,Trina  10088          1                1         0
4          Anderson, Carol   10069          0                2         0

   EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Salary  ...  \
0            1       5            4                       0   62506  ...
1            5       3            3                       0  104437  ...
2            5       5            3                       0   64955  ...
3            1       5            3                       0   64991  ...
4            5       5            3                       0   50825  ...

   EmpSatisfaction  SpecialProjectsCount LastPerformanceReview_Date  \
0                5                     0                  1/17/2019
1                3                     6                  2/24/2016
2                3                     0                  5/15/2012
3                5                     0                   1/3/2019
4                4                     0                   2/1/2016

  DaysLateLast30  Absences MaritalDesc_Divorced  MaritalDesc_Married  \
0              0         1                  0.0                  0.0
1              0        17                  0.0                  1.0
2              0         3                  0.0                  1.0
3              0        15                  0.0                  1.0
4              0         2                  1.0                  0.0

  MaritalDesc_Separated MaritalDesc_Single MaritalDesc_Widowed
0                   0.0                1.0                 0.0
1                   0.0                0.0                 0.0
2                   0.0                0.0                 0.0
3                   0.0                0.0                 0.0
4                   0.0                0.0                 0.0

[5 rows x 40 columns]

In [36]:
print(df_sklearn_encoded.isna().sum())
print(df_sklearn_encoded.duplicated().sum())
print(df_sklearn_encoded.shape)

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Sex                           311
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             207
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
MaritalDesc_Divorced            0
MaritalDesc_Married             0
MaritalDesc_Separated           0
MaritalDesc_Single              0
MaritalDesc_Widowed             0
dtype: int64
0
(311, 40)

In [37]:
df_sklearn_encoded.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,5,0,1/17/2019,0,1,0.0,0.0,0.0,1.0,0.0
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,3,6,2/24/2016,0,17,0.0,1.0,0.0,0.0,0.0
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,0,5/15/2012,0,3,0.0,1.0,0.0,0.0,0.0
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,5,0,1/3/2019,0,15,0.0,1.0,0.0,0.0,0.0
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,1.0,0.0,0.0,0.0,0.0

In [38]:
df_sklearn_encoded.describe()

,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,...,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
count,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,...,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000
mean,10156.000000,0.398714,0.810289,0.434084,2.392283,4.610932,2.977492,0.093248,69020.684887,0.334405,...,4.110000,3.890675,1.218650,0.414791,10.237942,0.096463,0.398714,0.038585,0.440514,0.025723
std,89.922189,0.490423,0.943239,0.496435,1.794383,1.083487,0.587072,0.291248,25156.636930,0.472542,...,0.789938,0.909241,2.349421,1.294519,5.852596,0.295701,0.490423,0.192915,0.497249,0.158564
min,10001.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,45046.000000,0.000000,...,1.120000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10078.500000,0.000000,0.000000,0.000000,1.000000,5.000000,3.000000,0.000000,55501.500000,0.000000,...,3.690000,3.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10156.000000,0.000000,1.000000,0.000000,1.000000,5.000000,3.000000,0.000000,62810.000000,0.000000,...,4.280000,4.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,10233.500000,1.000000,1.000000,1.000000,5.000000,5.000000,3.000000,0.000000,72036.000000,1.000000,...,4.700000,5.000000,0.000000,0.000000,15.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,10311.000000,1.000000,4.000000,1.000000,5.000000,6.000000,4.000000,1.000000,250000.000000,1.000000,...,5.000000,5.000000,8.000000,6.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [39]:
df_sklearn_encoded.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Sex', 'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'DateofHire',
       'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
       'ManagerName', 'ManagerID', 'RecruitmentSource', 'PerformanceScore',
       'EngagementSurvey', 'EmpSatisfaction', 'SpecialProjectsCount',
       'LastPerformanceReview_Date', 'DaysLateLast30', 'Absences',
       'MaritalDesc_Divorced', 'MaritalDesc_Married', 'MaritalDesc_Separated',
       'MaritalDesc_Single', 'MaritalDesc_Widowed'],
      dtype='object')

In [40]:
y = df_sklearn_encoded["Absences"]
y.head()

0     1
1    17
2     3
3    15
4     2
Name: Absences, dtype: int64

In [41]:
X = df_sklearn_encoded.drop("TermReason",axis=1)
X.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,5,0,1/17/2019,0,1,0.0,0.0,0.0,1.0,0.0
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,3,6,2/24/2016,0,17,0.0,1.0,0.0,0.0,0.0
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,0,5/15/2012,0,3,0.0,1.0,0.0,0.0,0.0
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,5,0,1/3/2019,0,15,0.0,1.0,0.0,0.0,0.0
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,1.0,0.0,0.0,0.0,0.0

In [42]:
df_sklearn_encoded.shape

(311, 40)

In [43]:
311*0.2

62.2

In [44]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [45]:
X_train.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
109,"Goeth, Amon",10228,1,1,1,1,3,3,0,74679,...,5,7,1/10/2019,0,20,0.0,1.0,0.0,0.0,0.0
247,"Sadki, Nore",10260,0,0,1,5,5,3,0,46428,...,5,0,2/5/2018,0,7,0.0,0.0,0.0,1.0,0.0
234,"Robertson, Peter",10224,1,1,1,5,5,3,0,55578,...,5,0,1/6/2012,0,13,0.0,1.0,0.0,0.0,0.0
202,"Nguyen, Dheepa",10042,0,0,0,1,6,3,0,63695,...,5,0,1/25/2019,0,2,0.0,0.0,0.0,1.0,0.0
78,"Dunn, Amy",10105,0,0,0,1,5,3,0,75188,...,4,0,1/15/2019,0,4,0.0,0.0,0.0,1.0,0.0

In [46]:
print(X_train.shape)
print(X_test.shape)

(248, 39)
(63, 39)

In [47]:
print(y_train.shape)
print(y_test.shape)

(248,)
(63,)

In [48]:
df_sklearn_encoded.describe()

,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,...,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
count,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,...,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000
mean,10156.000000,0.398714,0.810289,0.434084,2.392283,4.610932,2.977492,0.093248,69020.684887,0.334405,...,4.110000,3.890675,1.218650,0.414791,10.237942,0.096463,0.398714,0.038585,0.440514,0.025723
std,89.922189,0.490423,0.943239,0.496435,1.794383,1.083487,0.587072,0.291248,25156.636930,0.472542,...,0.789938,0.909241,2.349421,1.294519,5.852596,0.295701,0.490423,0.192915,0.497249,0.158564
min,10001.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,45046.000000,0.000000,...,1.120000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10078.500000,0.000000,0.000000,0.000000,1.000000,5.000000,3.000000,0.000000,55501.500000,0.000000,...,3.690000,3.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10156.000000,0.000000,1.000000,0.000000,1.000000,5.000000,3.000000,0.000000,62810.000000,0.000000,...,4.280000,4.000000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,10233.500000,1.000000,1.000000,1.000000,5.000000,5.000000,3.000000,0.000000,72036.000000,1.000000,...,4.700000,5.000000,0.000000,0.000000,15.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,10311.000000,1.000000,4.000000,1.000000,5.000000,6.000000,4.000000,1.000000,250000.000000,1.000000,...,5.000000,5.000000,8.000000,6.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [49]:
X_train.describe()

,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,...,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
count,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,...,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000,248.000000
mean,10156.741935,0.427419,0.814516,0.435484,2.379032,4.592742,2.967742,0.100806,68305.274194,0.330645,...,4.072177,3.858871,1.209677,0.463710,9.907258,0.092742,0.427419,0.040323,0.419355,0.020161
std,91.400650,0.495704,0.907610,0.496823,1.791083,1.087036,0.629060,0.301681,24192.636818,0.471397,...,0.812828,0.926577,2.309194,1.349274,5.792242,0.290657,0.495704,0.197112,0.494451,0.140836
min,10001.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,45046.000000,0.000000,...,1.120000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10076.750000,0.000000,0.000000,0.000000,1.000000,5.000000,3.000000,0.000000,55105.000000,0.000000,...,3.600000,3.000000,0.000000,0.000000,4.750000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10159.500000,0.000000,1.000000,0.000000,1.000000,5.000000,3.000000,0.000000,62586.500000,0.000000,...,4.200000,4.000000,0.000000,0.000000,9.500000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,10233.250000,1.000000,1.000000,1.000000,5.000000,5.000000,3.000000,0.000000,71797.000000,1.000000,...,4.657500,5.000000,0.000000,0.000000,15.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,10311.000000,1.000000,4.000000,1.000000,5.000000,6.000000,4.000000,1.000000,250000.000000,1.000000,...,5.000000,5.000000,8.000000,6.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [50]:
df_sklearn_encoded.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,5,0,1/17/2019,0,1,0.0,0.0,0.0,1.0,0.0
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,3,6,2/24/2016,0,17,0.0,1.0,0.0,0.0,0.0
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,0,5/15/2012,0,3,0.0,1.0,0.0,0.0,0.0
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,5,0,1/3/2019,0,15,0.0,1.0,0.0,0.0,0.0
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,1.0,0.0,0.0,0.0,0.0

In [51]:
X_test.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
290,"Vega, Vincent",10144,0,2,1,1,5,3,0,88976,...,3,0,2/27/2019,0,19,1.0,0.0,0.0,0.0,0.0
9,"Bacong, Alejandro",10250,0,2,1,1,3,3,0,50178,...,5,6,2/18/2019,0,16,1.0,0.0,0.0,0.0,0.0
57,"Costello, Frank",10193,1,1,1,1,3,3,0,83552,...,3,6,1/22/2019,0,2,0.0,1.0,0.0,0.0,0.0
60,"Daneault, Lynn",10099,0,0,0,1,6,3,0,65729,...,4,0,1/24/2019,0,8,0.0,0.0,0.0,1.0,0.0
25,"Booth, Frank",10199,0,0,1,4,3,3,0,103613,...,5,7,1/10/2016,0,2,0.0,0.0,0.0,1.0,0.0

In [52]:
X_test.describe()

,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,...,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences,MaritalDesc_Divorced,MaritalDesc_Married,MaritalDesc_Separated,MaritalDesc_Single,MaritalDesc_Widowed
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,...,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,10153.079365,0.285714,0.793651,0.428571,2.444444,4.682540,3.015873,0.063492,71836.904762,0.349206,...,4.258889,4.015873,1.253968,0.222222,11.539683,0.111111,0.285714,0.031746,0.523810,0.047619
std,84.484070,0.455383,1.080005,0.498847,1.820827,1.075015,0.380664,0.245805,28678.929504,0.480548,...,0.677981,0.832642,2.520677,1.038679,5.953653,0.316794,0.455383,0.176731,0.503444,0.214669
min,10002.000000,0.000000,0.000000,0.000000,1.000000,1.000000,2.000000,0.000000,46430.000000,0.000000,...,2.340000,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10083.000000,0.000000,0.000000,0.000000,1.000000,5.000000,3.000000,0.000000,57571.500000,0.000000,...,3.965000,3.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10143.000000,0.000000,0.000000,0.000000,1.000000,5.000000,3.000000,0.000000,63322.000000,0.000000,...,4.300000,4.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,10228.500000,1.000000,1.000000,1.000000,5.000000,5.000000,3.000000,0.000000,73425.000000,1.000000,...,4.820000,5.000000,0.000000,0.000000,16.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,10293.000000,1.000000,4.000000,1.000000,5.000000,6.000000,4.000000,1.000000,220450.000000,1.000000,...,5.000000,5.000000,8.000000,6.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [74]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Example data (replace with your actual dataset)
df = pd.DataFrame({
    'Age': [25, 30, 35, 40, 45],
    'Company': [1, 2, 3, 4, 5],
    'Employee_Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],  # Categorical column (DO NOT SCALE)
    'Department': ['Sales', 'IT', 'HR', 'IT', 'Sales']  # Categorical column (DO NOT SCALE)
})

# Split X and y
X = df[['Age', 'Company', 'Employee_Name', 'Department']]
y = [0, 1, 0, 1, 0]  # Dummy target variable (could be your actual target)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the StandardScaler
scaler = StandardScaler()

# Select the columns to scale
columns_to_scale = ['Age', 'Company']

# Copy the original DataFrame to avoid modifying the original data
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# Scale the specified columns in X_train and X_test
X_train_scaled[columns_to_scale] = scaler.fit_transform(X_train[columns_to_scale])
X_test_scaled[columns_to_scale] = scaler.transform(X_test[columns_to_scale])

# Display the scaled DataFrame
print("\nScaled X_train (Age and Company are scaled, others remain the same):")
print(X_train_scaled)

print("\nScaled X_test (Age and Company are scaled, others remain the same):")
print(X_test_scaled)

Scaled X_train (Age and Company are scaled, others remain the same):
        Age   Company Employee_Name Department
4  1.183216  1.183216       Charlie      Sales
2 -0.169031 -0.169031           Bob         HR
0 -1.521278 -1.521278          John      Sales
3  0.507093  0.507093           Eve         IT

Scaled X_test (Age and Company are scaled, others remain the same):
        Age   Company Employee_Name Department
1 -0.845154 -0.845154         Alice         IT

   Age  Company Employee_Name Department
4   45        5       Charlie      Sales
2   35        3           Bob         HR
0   25        1          John      Sales
3   40        4           Eve         IT

In [75]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the Linear Regression model
regressor = LinearRegression()

# Train the model using X_train_scaled and y_train
regressor.fit(X_train_scaled[['Age', 'Company']], y_train)  # Train only on scaled features

# Predict the target variable for the test data
y_pred = regressor.predict(X_test_scaled[['Age', 'Company']])  # Predict only using scaled features

# Print predictions
print("\nPredictions on X_test_scaled:")
print(y_pred)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nMean Squared Error:", mse)
print("R-squared:", r2)

Predictions on X_test_scaled:
[0.14285714]

Mean Squared Error: 0.7346938775510206
R-squared: nan

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

In [80]:
# calculate MAE, MSE, RMSE, R2


import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Example data (replace with your actual dataset)
df = pd.DataFrame({
    'Age': [25, 30, 35, 40, 45],
    'Company': [1, 2, 3, 4, 5],
    'Employee_Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],  # Categorical column (DO NOT SCALE)
    'Department': ['Sales', 'IT', 'HR', 'IT', 'Sales']  # Categorical column (DO NOT SCALE)
})

# Split X and y
X = df[['Age', 'Company', 'Employee_Name', 'Department']]
y = [0, 1, 0, 1, 0]  # Dummy target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 1: Scaling the numerical features (Age and Company)
scaler = StandardScaler()
columns_to_scale = ['Age', 'Company']

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[columns_to_scale] = scaler.fit_transform(X_train[columns_to_scale])
X_test_scaled[columns_to_scale] = scaler.transform(X_test[columns_to_scale])

# Step 2: Linear Regression Model
regressor = LinearRegression()

# Train the model using X_train_scaled and y_train
regressor.fit(X_train_scaled[['Age', 'Company']], y_train)

# Step 3: Making Predictions
y_pred = regressor.predict(X_test_scaled[['Age', 'Company']])

# Calculate the MAE (Mean Absolute Error)
mae = mean_absolute_error(y_test, y_pred)

# Calculate the MSE (Mean Squared Error)
mse = mean_squared_error(y_test, y_pred)

# Calculate the RMSE (Root Mean Squared Error)
rmse = np.sqrt(mse)

# Calculate the R-squared (R²) score
r2 = r2_score(y_test, y_pred)

# Print the results
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R-squared (R²):", r2)

Mean Absolute Error (MAE): 0.8571428571428572
Mean Squared Error (MSE): 0.7346938775510206
Root Mean Squared Error (RMSE): 0.8571428571428572
R-squared (R²): nan

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

In [83]:
df.head()

   Age  Company Employee_Name Department
0   25        1          John      Sales
1   30        2         Alice         IT
2   35        3           Bob         HR
3   40        4           Eve         IT
4   45        5       Charlie      Sales

In [88]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Example data (replace with your actual dataset)
df = pd.DataFrame({
    'Age': [25, 30, 35, 40, 45],
    'Company': [1, 2, 3, 4, 5],
    'Employee_Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],  # Categorical column (DO NOT SCALE)
    'Department': ['Sales', 'IT', 'HR', 'IT', 'Sales']  # Categorical column (DO NOT SCALE)
})

# Split X and y
X = df[['Age', 'Company', 'Employee_Name', 'Department']]
y = [0, 1, 0, 1, 0]  # Dummy target variable (replace with your actual target)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 1: Scaling the numerical features (Age and Company)
scaler = StandardScaler()
columns_to_scale = ['Age', 'Company']

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[columns_to_scale] = scaler.fit_transform(X_train[columns_to_scale])
X_test_scaled[columns_to_scale] = scaler.transform(X_test[columns_to_scale])

# Initialize models
lr = LinearRegression()
svm = SVR()
knn = KNeighborsRegressor()
dt = DecisionTreeRegressor()

# Train each model and evaluate
models = {'Linear Regression': lr, 'SVM': svm, 'KNN': knn, 'Decision Tree': dt}
results = {}

for model_name, model in models.items():
    # Fit the model
    model.fit(X_train_scaled[['Age', 'Company']], y_train)

    # Make predictions
y_pred = model.predict(X_test_scaled[['Age', 'Company']])

    # Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

results[model_name] = {
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2': r2
    }

# Print the results
for model_name, metrics in results.items():
    print(f"\n{model_name} Results:")
    for metric_name, value in metrics.items():
        print(f"{metric_name}: {value}")

Decision Tree Results:
MAE: 1.0
MSE: 1.0
RMSE: 1.0
R2: nan

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

In [89]:
help(SVR)

Help on class SVR in module sklearn.svm._classes:

class SVR(sklearn.base.RegressorMixin, sklearn.svm._base.BaseLibSVM)
 |  SVR(*, kernel='rbf', degree=3, gamma='scale', coef0=0.0, tol=0.001, C=1.0, epsilon=0.1, shrinking=True, cache_size=200, verbose=False, max_iter=-1)
 |
 |  Epsilon-Support Vector Regression.
 |
 |  The free parameters in the model are C and epsilon.
 |
 |  The implementation is based on libsvm. The fit time complexity
 |  is more than quadratic with the number of samples which makes it hard
 |  to scale to datasets with more than a couple of 10000 samples. For large
 |  datasets consider using :class:`~sklearn.svm.LinearSVR` or
 |  :class:`~sklearn.linear_model.SGDRegressor` instead, possibly after a
 |  :class:`~sklearn.kernel_approximation.Nystroem` transformer or
 |  other :ref:`kernel_approximation`.
 |
 |  Read more in the :ref:`User Guide <svm_regression>`.
 |
 |  Parameters
 |  ----------
 |  kernel : {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable,          default='rbf'
 |       Specifies the kernel type to be used in the algorithm.
 |       If none is given, 'rbf' will be used. If a callable is given it is
 |       used to precompute the kernel matrix.
 |
 |  degree : int, default=3
 |      Degree of the polynomial kernel function ('poly').
 |      Must be non-negative. Ignored by all other kernels.
 |
 |  gamma : {'scale', 'auto'} or float, default='scale'
 |      Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.
 |
 |      - if ``gamma='scale'`` (default) is passed then it uses
 |        1 / (n_features * X.var()) as value of gamma,
 |      - if 'auto', uses 1 / n_features
 |      - if float, must be non-negative.
 |
 |      .. versionchanged:: 0.22
 |         The default value of ``gamma`` changed from 'auto' to 'scale'.
 |
 |  coef0 : float, default=0.0
 |      Independent term in kernel function.
 |      It is only significant in 'poly' and 'sigmoid'.
 |
 |  tol : float, default=1e-3
 |      Tolerance for stopping criterion.
 |
 |  C : float, default=1.0
 |      Regularization parameter. The strength of the regularization is
 |      inversely proportional to C. Must be strictly positive.
 |      The penalty is a squared l2. For an intuitive visualization of the
 |      effects of scaling the regularization parameter C, see
 |      :ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.
 |
 |  epsilon : float, default=0.1
 |       Epsilon in the epsilon-SVR model. It specifies the epsilon-tube
 |       within which no penalty is associated in the training loss function
 |       with points predicted within a distance epsilon from the actual
 |       value. Must be non-negative.
 |
 |  shrinking : bool, default=True
 |      Whether to use the shrinking heuristic.
 |      See the :ref:`User Guide <shrinking_svm>`.
 |
 |  cache_size : float, default=200
 |      Specify the size of the kernel cache (in MB).
 |
 |  verbose : bool, default=False
 |      Enable verbose output. Note that this setting takes advantage of a
 |      per-process runtime setting in libsvm that, if enabled, may not work
 |      properly in a multithreaded context.
 |
 |  max_iter : int, default=-1
 |      Hard limit on iterations within solver, or -1 for no limit.
 |
 |  Attributes
 |  ----------
 |  coef_ : ndarray of shape (1, n_features)
 |      Weights assigned to the features (coefficients in the primal
 |      problem). This is only available in the case of a linear kernel.
 |
 |      `coef_` is readonly property derived from `dual_coef_` and
 |      `support_vectors_`.
 |
 |  dual_coef_ : ndarray of shape (1, n_SV)
 |      Coefficients of the support vector in the decision function.
 |
 |  fit_status_ : int
 |      0 if correctly fitted, 1 otherwise (will raise warning)
 |
 |  intercept_ : ndarray of shape (1,)
 |      Constants in decision function.
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  n_iter_ : int
 |      Number of iterations run by the optimization routine to fit the model.
 |
 |      .. versionadded:: 1.1
 |
 |  n_support_ : ndarray of shape (1,), dtype=int32
 |      Number of support vectors.
 |
 |  shape_fit_ : tuple of int of shape (n_dimensions_of_X,)
 |      Array dimensions of training vector ``X``.
 |
 |  support_ : ndarray of shape (n_SV,)
 |      Indices of support vectors.
 |
 |  support_vectors_ : ndarray of shape (n_SV, n_features)
 |      Support vectors.
 |
 |  See Also
 |  --------
 |  NuSVR : Support Vector Machine for regression implemented using libsvm
 |      using a parameter to control the number of support vectors.
 |
 |  LinearSVR : Scalable Linear Support Vector Machine for regression
 |      implemented using liblinear.
 |
 |  References
 |  ----------
 |  .. [1] `LIBSVM: A Library for Support Vector Machines
 |      <http://www.csie.ntu.edu.tw/~cjlin/papers/libsvm.pdf>`_
 |
 |  .. [2] `Platt, John (1999). "Probabilistic Outputs for Support Vector
 |      Machines and Comparisons to Regularized Likelihood Methods"
 |      <https://citeseerx.ist.psu.edu/doc_view/pid/42e5ed832d4310ce4378c44d05570439df28a393>`_
 |
 |  Examples
 |  --------
 |  >>> from sklearn.svm import SVR
 |  >>> from sklearn.pipeline import make_pipeline
 |  >>> from sklearn.preprocessing import StandardScaler
 |  >>> import numpy as np
 |  >>> n_samples, n_features = 10, 5
 |  >>> rng = np.random.RandomState(0)
 |  >>> y = rng.randn(n_samples)
 |  >>> X = rng.randn(n_samples, n_features)
 |  >>> regr = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.2))
 |  >>> regr.fit(X, y)
 |  Pipeline(steps=[('standardscaler', StandardScaler()),
 |                  ('svr', SVR(epsilon=0.2))])
 |
 |  Method resolution order:
 |      SVR
 |      sklearn.base.RegressorMixin
 |      sklearn.svm._base.BaseLibSVM
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._estimator_html_repr._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, kernel='rbf', degree=3, gamma='scale', coef0=0.0, tol=0.001, C=1.0, epsilon=0.1, shrinking=True, cache_size=200, verbose=False, max_iter=-1)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  set_fit_request(self: sklearn.svm._classes.SVR, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.svm._classes.SVR
 |      Request metadata passed to the ``fit`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``fit`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``fit``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``fit``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  set_score_request(self: sklearn.svm._classes.SVR, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.svm._classes.SVR
 |      Request metadata passed to the ``score`` method.
 |
 |      Note that this method is only relevant if
 |      ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please see :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``score`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``score``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      .. note::
 |          This method is only relevant if this estimator is used as a
 |          sub-estimator of a meta-estimator, e.g. used inside a
 |          :class:`~sklearn.pipeline.Pipeline`. Otherwise it has no effect.
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``score``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  unused_param = 'random_state'
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.RegressorMixin:
 |
 |  score(self, X, y, sample_weight=None)
 |      Return the coefficient of determination of the prediction.
 |
 |      The coefficient of determination :math:`R^2` is defined as
 |      :math:`(1 - \frac{u}{v})`, where :math:`u` is the residual
 |      sum of squares ``((y_true - y_pred)** 2).sum()`` and :math:`v`
 |      is the total sum of squares ``((y_true - y_true.mean()) ** 2).sum()``.
 |      The best possible score is 1.0 and it can be negative (because the
 |      model can be arbitrarily worse). A constant model that always predicts
 |      the expected value of `y`, disregarding the input features, would get
 |      a :math:`R^2` score of 0.0.
 |
 |      Parameters
 |      ----------
 |      X : array-like of shape (n_samples, n_features)
 |          Test samples. For some estimators this may be a precomputed
 |          kernel matrix or a list of generic objects instead with shape
 |          ``(n_samples, n_samples_fitted)``, where ``n_samples_fitted``
 |          is the number of samples used in the fitting for the estimator.
 |
 |      y : array-like of shape (n_samples,) or (n_samples, n_outputs)
 |          True values for `X`.
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Sample weights.
 |
 |      Returns
 |      -------
 |      score : float
 |          :math:`R^2` of ``self.predict(X)`` w.r.t. `y`.
 |
 |      Notes
 |      -----
 |      The :math:`R^2` score used when calling ``score`` on a regressor uses
 |      ``multioutput='uniform_average'`` from version 0.23 to keep consistent
 |      with default value of :func:`~sklearn.metrics.r2_score`.
 |      This influences the ``score`` method of all the multioutput
 |      regressors (except for
 |      :class:`~sklearn.multioutput.MultiOutputRegressor`).
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.RegressorMixin:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.svm._base.BaseLibSVM:
 |
 |  fit(self, X, y, sample_weight=None)
 |      Fit the SVM model according to the given training data.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)                 or (n_samples, n_samples)
 |          Training vectors, where `n_samples` is the number of samples
 |          and `n_features` is the number of features.
 |          For kernel="precomputed", the expected shape of X is
 |          (n_samples, n_samples).
 |
 |      y : array-like of shape (n_samples,)
 |          Target values (class labels in classification, real numbers in
 |          regression).
 |
 |      sample_weight : array-like of shape (n_samples,), default=None
 |          Per-sample weights. Rescale C per sample. Higher weights
 |          force the classifier to put more emphasis on these points.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted estimator.
 |
 |      Notes
 |      -----
 |      If X and y are not C-ordered and contiguous arrays of np.float64 and
 |      X is not a scipy.sparse.csr_matrix, X and/or y may be copied.
 |
 |      If X is a dense array, then the other methods will not support sparse
 |      matrices as input.
 |
 |  predict(self, X)
 |      Perform regression on samples in X.
 |
 |      For an one-class model, +1 (inlier) or -1 (outlier) is returned.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          For kernel="precomputed", the expected shape of X is
 |          (n_samples_test, n_samples_train).
 |
 |      Returns
 |      -------
 |      y_pred : ndarray of shape (n_samples,)
 |          The predicted values.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from sklearn.svm._base.BaseLibSVM:
 |
 |  coef_
 |      Weights assigned to the features when `kernel="linear"`.
 |
 |      Returns
 |      -------
 |      ndarray of shape (n_features, n_classes)
 |
 |  n_support_
 |      Number of support vectors for each class.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  __sklearn_clone__(self)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  get_metadata_routing(self)
 |      Get metadata routing of this object.
 |
 |      Please check :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      Returns
 |      -------
 |      routing : MetadataRequest
 |          A :class:`~sklearn.utils.metadata_routing.MetadataRequest` encapsulating
 |          routing information.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  __init_subclass__(**kwargs) from abc.ABCMeta
 |      Set the ``set_{method}_request`` methods.
 |
 |      This uses PEP-487 [1]_ to set the ``set_{method}_request`` methods. It
 |      looks for the information available in the set default values which are
 |      set using ``__metadata_request__*`` class attributes, or inferred
 |      from method signatures.
 |
 |      The ``__metadata_request__*`` class attributes are used when a method
 |      does not explicitly accept a metadata through its arguments or if the
 |      developer would like to specify a request value for those metadata
 |      which are different from the default ``None``.
 |
 |      References
 |      ----------
 |      .. [1] https://www.python.org/dev/peps/pep-0487

In [92]:
knn = KNeighborsRegressor(n_neighbors=3)  # Change n_neighbors as needed

# Train the model
knn.fit(X_train_scaled[['Age', 'Company']], y_train)

# Step 3: Make predictions
# Ensure the prediction data is in the correct shape (2D array)
X_test_features = X_test_scaled[['Age', 'Company']].values  # Convert to numpy array

# Make predictions
y_pred = knn.predict(X_test_features)

# Ensure y_pred is 1D (flatten if necessary)
y_pred = np.ravel(y_pred)

# Step 4: Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Print the results
print(f"KNN Regression Results:")
print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")

KNN Regression Results:
MAE: 0.6666666666666667
MSE: 0.44444444444444453
RMSE: 0.6666666666666667
R2: nan

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

In [100]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Example data (replace with your actual dataset)
df = pd.DataFrame({
    'Age': [25, 30, 35, 40, 45],
    'Company': [1, 2, 3, 4, 5],
    'Employee_Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],  # Categorical column
    'Department': ['Sales', 'IT', 'HR', 'IT', 'Sales']  # Categorical column
})

# Target variable (replace with your actual target)
y = [0, 1, 0, 1, 0]

# Split into features and target variable
X = df[['Age', 'Company', 'Employee_Name', 'Department']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 1: Create the column transformer for OneHotEncoding categorical variables
# Numeric features: 'Age', 'Company'
# Categorical features: 'Employee_Name', 'Department'
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Age', 'Company']),  # Standard scaling for numeric columns
        ('cat', OneHotEncoder(handle_unknown='ignore'), ['Employee_Name', 'Department'])  # OneHotEncoding with handling unknown categories
    ])

# Step 2: Create a pipeline that first applies preprocessing then fits the Random Forest model
model = Pipeline(steps=[
    ('preprocessor', preprocessor),  # Apply preprocessing
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))  # Random Forest model
])

# Step 3: Train the model
model.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 5: Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Print the results
print(f"Random Forest Regression Results:")
print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")

Random Forest Regression Results:
MAE: 0.6599999999999999
MSE: 0.4355999999999999
RMSE: 0.6599999999999999
R2: nan

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_regression.py:1211: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

In [101]:
# save model

import pickle
pickle.dump(lr,open("lr_model.pkl","wb"))